package local.spotify.unified;
import java.util.Locale;
public final class ProfileText {
 public static String get(String key){
  String[] keys={"profiles","note","loading","add","back","active","choose","rename","remove","cancel","save","name","error","switching","confirmAdd","yes","empty","retry","launchError","loginRetry"};
  String[][] values={
   {"Accounts","Experimental: switching between different accounts has not been verified.","Loading profiles…","Add account · QR","Back to Spotify","Active","Switch account","Rename","Remove","Cancel","Save","Profile name","Could not update profiles. Your saved profiles have been kept. Try again.","Opening account…","Music will stop while you sign in to another account. You can return to a saved profile using this screen.","Continue","Add your Spotify account using QR sign-in.","Retry","Spotify did not open. Your profiles are saved. Tap Retry to continue.","Sign-in is taking longer. Tap Log In to try again."},
   {"Акаунти","Експериментальна функція: перемикання між різними акаунтами ще не перевірене.","Завантаження профілів…","Додати акаунт · QR","Назад до Spotify","Активний","Переключити акаунт","Перейменувати","Видалити","Скасувати","Зберегти","Ім’я профілю","Не вдалося оновити профілі. Збережені профілі залишилися. Спробуй ще раз.","Відкриття акаунта…","Музика зупиниться на час входу в інший акаунт. Повернутися до збереженого профілю можна на цьому екрані.","Продовжити","Додай свій акаунт Spotify через QR-код.","Повторити","Spotify не відкрився. Профілі збережено. Натисни «Повторити», щоб продовжити.","Вхід триває довше. Натисни «Увійти», щоб спробувати ще раз."},
   {"Аккаунты","Экспериментальная функция: переключение между разными аккаунтами ещё не проверено.","Загрузка профилей…","Добавить аккаунт · QR","Назад в Spotify","Активный","Переключить аккаунт","Переименовать","Удалить","Отмена","Сохранить","Имя профиля","Не удалось обновить профили. Сохранённые профили остались. Попробуй ещё раз.","Открытие аккаунта…","Музыка остановится на время входа в другой аккаунт. Вернуться к сохранённому профилю можно на этом экране.","Продолжить","Добавь свой аккаунт Spotify через QR-код.","Повторить","Spotify не открылся. Профили сохранены. Нажми «Повторить», чтобы продолжить.","Вход занимает больше времени. Нажми «Войти», чтобы попробовать снова."},
   {"الحسابات","ميزة تجريبية: لم يتم التحقق من التبديل بين حسابات مختلفة.","جارٍ تحميل الملفات…","إضافة حساب · QR","العودة إلى Spotify","نشط","تبديل الحساب","إعادة تسمية","إزالة","إلغاء","حفظ","اسم الملف","تعذر تحديث الملفات. تم الاحتفاظ بالملفات المحفوظة. حاول مرة أخرى.","جارٍ فتح الحساب…","ستتوقف الموسيقى أثناء تسجيل الدخول إلى حساب آخر. يمكنك العودة إلى ملف محفوظ من هذه الشاشة.","متابعة","أضف حساب Spotify باستخدام رمز QR.","إعادة المحاولة","لم يفتح Spotify. تم حفظ ملفاتك. اضغط إعادة المحاولة للمتابعة.","يستغرق تسجيل الدخول وقتاً أطول. اضغط تسجيل الدخول للمحاولة مجدداً."},
   {"账号","实验性功能：尚未验证不同账号之间的切换。","正在加载档案…","添加账号 · QR","返回 Spotify","当前账号","切换账号","重命名","移除","取消","保存","档案名称","无法更新档案。已保留保存的档案，请重试。","正在打开账号…","登录其他账号期间音乐将停止。可从此页面返回已保存的档案。","继续","通过二维码登录添加 Spotify 账号。","重试","Spotify 未打开。档案已保存，请点击重试继续。","登录时间较长，请点击登录重试。"}
  };
  String lang=Locale.getDefault().getLanguage();int row=lang.equals("uk")?1:lang.equals("ru")?2:lang.equals("ar")?3:lang.equals("zh")?4:0;
  for(int i=0;i<keys.length;i++)if(keys[i].equals(key))return values[row][i];return key;
 }
}
